packages:
  irk_capture: github://KyleTeal/irk-capture/irk-capture-package.yaml@main

substitutions:
  board_type: esp32dev
  ble_name: "JBL Tune"
  start_on_boot: false




wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  ap:
    ssid: "IRK-Capture-AP"
    password: !secret ap_pass

api:
  encryption:
    key: !secret encrypt_key

ota:
  - platform: esphome
    password: !secret ota_pass
